/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <math.h>

#include "edu_rice_bold_service_broadcast_types.h"
#include <thrift/c_glib/thrift.h>

/* return the name of the constant */
const char *
toString_PushReplyCmd(int value) 
{
  static __thread char buf[16] = {0};
  switch(value) {
  case EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD_PUSH:return "EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD_PUSH";
  case EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD_POSTPONE:return "EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD_POSTPONE";
  case EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD_DENY:return "EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD_DENY";
  default: g_snprintf(buf, 16, "%d", value); return buf;
  }
}

enum _edu_rice_bold_serviceBcdInfoProperties
{
  PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_0,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_ID,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_SIZE
};

/* reads a bcd_info object */
static gint32
edu_rice_bold_service_bcd_info_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_bold_serviceBcdInfo * this_object = EDU_RICE_BOLD_SERVICE_BCD_INFO(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRING)
        {
          if (this_object->id != NULL)
          {
            g_free(this_object->id);
            this_object->id = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->id, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_id = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_I32)
        {
          if ((ret = thrift_protocol_read_i32 (protocol, &this_object->size, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_size = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_bold_service_bcd_info_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_bold_serviceBcdInfo * this_object = EDU_RICE_BOLD_SERVICE_BCD_INFO(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "BcdInfo", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "id", T_STRING, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->id, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "size", T_I32, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i32 (protocol, this_object->size, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_bold_service_bcd_info_set_property (GObject *object,
                                             guint property_id,
                                             const GValue *value,
                                             GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdInfo *self = EDU_RICE_BOLD_SERVICE_BCD_INFO (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_ID:
      if (self->id != NULL)
        g_free (self->id);
      self->id = g_value_dup_string (value);
      self->__isset_id = TRUE;
      break;

    case PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_SIZE:
      self->size = g_value_get_int (value);
      self->__isset_size = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_bold_service_bcd_info_get_property (GObject *object,
                                             guint property_id,
                                             GValue *value,
                                             GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdInfo *self = EDU_RICE_BOLD_SERVICE_BCD_INFO (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_ID:
      g_value_set_string (value, self->id);
      break;

    case PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_SIZE:
      g_value_set_int (value, self->size);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_bold_service_bcd_info_instance_init (edu_rice_bold_serviceBcdInfo * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->id = NULL;
  object->__isset_id = FALSE;
  object->size = 0;
  object->__isset_size = FALSE;
}

static void 
edu_rice_bold_service_bcd_info_finalize (GObject *object)
{
  edu_rice_bold_serviceBcdInfo *tobject = EDU_RICE_BOLD_SERVICE_BCD_INFO (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->id != NULL)
  {
    g_free(tobject->id);
    tobject->id = NULL;
  }
}

static void
edu_rice_bold_service_bcd_info_class_init (edu_rice_bold_serviceBcdInfoClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_bold_service_bcd_info_read;
  struct_class->write = edu_rice_bold_service_bcd_info_write;

  gobject_class->finalize = edu_rice_bold_service_bcd_info_finalize;
  gobject_class->get_property = edu_rice_bold_service_bcd_info_get_property;
  gobject_class->set_property = edu_rice_bold_service_bcd_info_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_ID,
     g_param_spec_string ("id",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_BCD_INFO_SIZE,
     g_param_spec_int ("size",
                       NULL,
                       NULL,
                       G_MININT32,
                       G_MAXINT32,
                       0,
                       G_PARAM_READWRITE));
}

GType
edu_rice_bold_service_bcd_info_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_bold_serviceBcdInfoClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_bold_service_bcd_info_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_bold_serviceBcdInfo),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_bold_service_bcd_info_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_bold_serviceBcdInfoType",
                                   &type_info, 0);
  }

  return type;
}

enum _edu_rice_bold_servicePushReplyProperties
{
  PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_0,
  PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_XID,
  PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD
};

/* reads a push_reply object */
static gint32
edu_rice_bold_service_push_reply_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_bold_servicePushReply * this_object = EDU_RICE_BOLD_SERVICE_PUSH_REPLY(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I32)
        {
          if ((ret = thrift_protocol_read_i32 (protocol, &this_object->xid, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_xid = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_I32)
        {
          gint32 ecast0;
          if ((ret = thrift_protocol_read_i32 (protocol, &ecast0, error)) < 0)
            return -1;
          xfer += ret;
          this_object->cmd = (edu_rice_bold_servicePushReplyCmd)ecast0;
          this_object->__isset_cmd = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_bold_service_push_reply_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_bold_servicePushReply * this_object = EDU_RICE_BOLD_SERVICE_PUSH_REPLY(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "PushReply", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "xid", T_I32, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i32 (protocol, this_object->xid, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "cmd", T_I32, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i32 (protocol, (gint32) this_object->cmd, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_bold_service_push_reply_set_property (GObject *object,
                                               guint property_id,
                                               const GValue *value,
                                               GParamSpec *pspec)
{
  edu_rice_bold_servicePushReply *self = EDU_RICE_BOLD_SERVICE_PUSH_REPLY (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_XID:
      self->xid = g_value_get_int (value);
      self->__isset_xid = TRUE;
      break;

    case PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD:
      self->cmd = g_value_get_int (value);
      self->__isset_cmd = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_bold_service_push_reply_get_property (GObject *object,
                                               guint property_id,
                                               GValue *value,
                                               GParamSpec *pspec)
{
  edu_rice_bold_servicePushReply *self = EDU_RICE_BOLD_SERVICE_PUSH_REPLY (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_XID:
      g_value_set_int (value, self->xid);
      break;

    case PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD:
      g_value_set_int (value, self->cmd);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_bold_service_push_reply_instance_init (edu_rice_bold_servicePushReply * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->xid = 0;
  object->__isset_xid = FALSE;
  object->__isset_cmd = FALSE;
}

static void 
edu_rice_bold_service_push_reply_finalize (GObject *object)
{
  edu_rice_bold_servicePushReply *tobject = EDU_RICE_BOLD_SERVICE_PUSH_REPLY (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
edu_rice_bold_service_push_reply_class_init (edu_rice_bold_servicePushReplyClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_bold_service_push_reply_read;
  struct_class->write = edu_rice_bold_service_push_reply_write;

  gobject_class->finalize = edu_rice_bold_service_push_reply_finalize;
  gobject_class->get_property = edu_rice_bold_service_push_reply_get_property;
  gobject_class->set_property = edu_rice_bold_service_push_reply_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_XID,
     g_param_spec_int ("xid",
                       NULL,
                       NULL,
                       G_MININT32,
                       G_MAXINT32,
                       0,
                       G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_PUSH_REPLY_CMD,
     g_param_spec_int ("cmd",
                       NULL,
                       NULL,
                       0,
                       2,
                       0,
                       G_PARAM_READWRITE));
}

GType
edu_rice_bold_service_push_reply_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_bold_servicePushReplyClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_bold_service_push_reply_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_bold_servicePushReply),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_bold_service_push_reply_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_bold_servicePushReplyType",
                                   &type_info, 0);
  }

  return type;
}

/* constants */

enum _edu_rice_bold_serviceBcdServicePushArgsProperties
{
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_0,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_MASTER,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_SLAVES,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_DATA
};

/* reads a bcd_service_push_args object */
static gint32
edu_rice_bold_service_bcd_service_push_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_bold_serviceBcdServicePushArgs * this_object = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRING)
        {
          if (this_object->master != NULL)
          {
            g_free(this_object->master);
            this_object->master = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->master, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_master = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_SET)
        {
          {
            guint32 size;
            guint32 i;
            ThriftType element_type;

            if ((ret = thrift_protocol_read_set_begin (protocol, &element_type, &size, error)) < 0)
              return -1;
            xfer += ret;

            /* iterate through the set elements */
            for (i = 0; i < size; ++i)
            {
              edu_rice_bold_serviceServerID _elem1 = NULL;
              if (_elem1 != NULL)
              {
                g_free(_elem1);
                _elem1 = NULL;
              }

              if ((ret = thrift_protocol_read_string (protocol, &_elem1, error)) < 0)
                return -1;
              xfer += ret;
              g_hash_table_insert ((GHashTable *) this_object->slaves, (gpointer) _elem1, (gpointer) 1);
            }
            if ((ret = thrift_protocol_read_set_end (protocol, error)) < 0)
              return -1;
            xfer += ret;

          }
          this_object->__isset_slaves = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 3:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->data), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_data = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_bold_service_bcd_service_push_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_bold_serviceBcdServicePushArgs * this_object = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "BcdServicePushArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "master", T_STRING, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->master, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "slaves", T_SET, 2, error)) < 0)
    return -1;
  xfer += ret;
  {
    GList *key_list = NULL, *iter = NULL;
    edu_rice_bold_serviceServerID* keys;
    int i = 0, key_count;
    edu_rice_bold_serviceServerID elem;
    gpointer value;
    THRIFT_UNUSED_VAR (value);

    if ((ret = thrift_protocol_write_set_begin (protocol, T_STRING, (gint32) g_hash_table_size ((GHashTable *) this_object->slaves), error)) < 0)
      return -1;
    xfer += ret;
    g_hash_table_foreach ((GHashTable *) this_object->slaves, thrift_hash_table_get_keys, &key_list);
    key_count = g_list_length (key_list);
    keys = g_newa (edu_rice_bold_serviceServerID, key_count);
    for (iter = g_list_first (key_list); iter; iter = iter->next)
      keys[i++] = (edu_rice_bold_serviceServerID) iter->data;
    g_list_free (key_list);

    for (i = 0; i < key_count; ++i)
    {
      elem = keys[i];
      value = (gpointer) g_hash_table_lookup (((GHashTable *) this_object->slaves), (gpointer) elem);

      if ((ret = thrift_protocol_write_string (protocol, elem, error)) < 0)
        return -1;
    }
    if ((ret = thrift_protocol_write_set_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "data", T_STRUCT, 3, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->data), protocol, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_bold_service_bcd_service_push_args_set_property (GObject *object,
                                                          guint property_id,
                                                          const GValue *value,
                                                          GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServicePushArgs *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_MASTER:
      if (self->master != NULL)
        g_free (self->master);
      self->master = g_value_dup_string (value);
      self->__isset_master = TRUE;
      break;

    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_SLAVES:
      if (self->slaves != NULL)
        g_hash_table_unref (self->slaves);
      self->slaves = g_value_dup_boxed (value);
      self->__isset_slaves = TRUE;
      break;

    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_DATA:
      if (self->data != NULL)
        g_object_unref (self->data);
      self->data = g_value_dup_object (value);
      self->__isset_data = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_bold_service_bcd_service_push_args_get_property (GObject *object,
                                                          guint property_id,
                                                          GValue *value,
                                                          GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServicePushArgs *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_MASTER:
      g_value_set_string (value, self->master);
      break;

    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_SLAVES:
      g_value_set_boxed (value, self->slaves);
      break;

    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_DATA:
      g_value_set_object (value, self->data);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_bold_service_bcd_service_push_args_instance_init (edu_rice_bold_serviceBcdServicePushArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->master = NULL;
  object->__isset_master = FALSE;
  object->slaves = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
  object->__isset_slaves = FALSE;
  object->data = g_object_new (EDU_RICE_BOLD_SERVICE_TYPE_BCD_INFO, NULL);
  object->__isset_data = FALSE;
}

static void 
edu_rice_bold_service_bcd_service_push_args_finalize (GObject *object)
{
  edu_rice_bold_serviceBcdServicePushArgs *tobject = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->master != NULL)
  {
    g_free(tobject->master);
    tobject->master = NULL;
  }
  if (tobject->slaves != NULL)
  {
    g_hash_table_destroy (tobject->slaves);
    tobject->slaves = NULL;
  }
  if (tobject->data != NULL)
  {
    g_object_unref(tobject->data);
    tobject->data = NULL;
  }
}

static void
edu_rice_bold_service_bcd_service_push_args_class_init (edu_rice_bold_serviceBcdServicePushArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_bold_service_bcd_service_push_args_read;
  struct_class->write = edu_rice_bold_service_bcd_service_push_args_write;

  gobject_class->finalize = edu_rice_bold_service_bcd_service_push_args_finalize;
  gobject_class->get_property = edu_rice_bold_service_bcd_service_push_args_get_property;
  gobject_class->set_property = edu_rice_bold_service_bcd_service_push_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_MASTER,
     g_param_spec_string ("master",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_SLAVES,
     g_param_spec_boxed ("slaves",
                         NULL,
                         NULL,
                         G_TYPE_HASH_TABLE,
                         G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_ARGS_DATA,
     g_param_spec_object ("data",
                         NULL,
                         NULL,
                         EDU_RICE_BOLD_SERVICE_TYPE_BCD_INFO,
                         G_PARAM_READWRITE));
}

GType
edu_rice_bold_service_bcd_service_push_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_bold_serviceBcdServicePushArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_bold_service_bcd_service_push_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_bold_serviceBcdServicePushArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_bold_service_bcd_service_push_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_bold_serviceBcdServicePushArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _edu_rice_bold_serviceBcdServicePushResultProperties
{
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT_0,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT_SUCCESS
};

/* reads a bcd_service_push_result object */
static gint32
edu_rice_bold_service_bcd_service_push_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_bold_serviceBcdServicePushResult * this_object = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_STRUCT)
        {
          if ((ret = thrift_struct_read (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
          {
            return -1;
          }
          xfer += ret;
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_bold_service_bcd_service_push_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_bold_serviceBcdServicePushResult * this_object = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "BcdServicePushResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_STRUCT, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (this_object->success), protocol, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_bold_service_bcd_service_push_result_set_property (GObject *object,
                                                            guint property_id,
                                                            const GValue *value,
                                                            GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServicePushResult *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT_SUCCESS:
      if (self->success != NULL)
        g_object_unref (self->success);
      self->success = g_value_dup_object (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_bold_service_bcd_service_push_result_get_property (GObject *object,
                                                            guint property_id,
                                                            GValue *value,
                                                            GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServicePushResult *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT_SUCCESS:
      g_value_set_object (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_bold_service_bcd_service_push_result_instance_init (edu_rice_bold_serviceBcdServicePushResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = g_object_new (EDU_RICE_BOLD_SERVICE_TYPE_PUSH_REPLY, NULL);
  object->__isset_success = FALSE;
}

static void 
edu_rice_bold_service_bcd_service_push_result_finalize (GObject *object)
{
  edu_rice_bold_serviceBcdServicePushResult *tobject = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->success != NULL)
  {
    g_object_unref(tobject->success);
    tobject->success = NULL;
  }
}

static void
edu_rice_bold_service_bcd_service_push_result_class_init (edu_rice_bold_serviceBcdServicePushResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_bold_service_bcd_service_push_result_read;
  struct_class->write = edu_rice_bold_service_bcd_service_push_result_write;

  gobject_class->finalize = edu_rice_bold_service_bcd_service_push_result_finalize;
  gobject_class->get_property = edu_rice_bold_service_bcd_service_push_result_get_property;
  gobject_class->set_property = edu_rice_bold_service_bcd_service_push_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PUSH_RESULT_SUCCESS,
     g_param_spec_object ("success",
                         NULL,
                         NULL,
                         EDU_RICE_BOLD_SERVICE_TYPE_PUSH_REPLY,
                         G_PARAM_READWRITE));
}

GType
edu_rice_bold_service_bcd_service_push_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_bold_serviceBcdServicePushResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_bold_service_bcd_service_push_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_bold_serviceBcdServicePushResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_bold_service_bcd_service_push_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_bold_serviceBcdServicePushResultType",
                                   &type_info, 0);
  }

  return type;
}

enum _edu_rice_bold_serviceBcdServiceUnpushArgsProperties
{
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS_0,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS_XID
};

/* reads a bcd_service_unpush_args object */
static gint32
edu_rice_bold_service_bcd_service_unpush_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  edu_rice_bold_serviceBcdServiceUnpushArgs * this_object = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_I32)
        {
          if ((ret = thrift_protocol_read_i32 (protocol, &this_object->xid, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_xid = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
edu_rice_bold_service_bcd_service_unpush_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  edu_rice_bold_serviceBcdServiceUnpushArgs * this_object = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "BcdServiceUnpushArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "xid", T_I32, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_i32 (protocol, this_object->xid, error)) < 0)
    return -1;
  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
edu_rice_bold_service_bcd_service_unpush_args_set_property (GObject *object,
                                                            guint property_id,
                                                            const GValue *value,
                                                            GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServiceUnpushArgs *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS_XID:
      self->xid = g_value_get_int (value);
      self->__isset_xid = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_bold_service_bcd_service_unpush_args_get_property (GObject *object,
                                                            guint property_id,
                                                            GValue *value,
                                                            GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServiceUnpushArgs *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS_XID:
      g_value_set_int (value, self->xid);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
edu_rice_bold_service_bcd_service_unpush_args_instance_init (edu_rice_bold_serviceBcdServiceUnpushArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->xid = 0;
  object->__isset_xid = FALSE;
}

static void 
edu_rice_bold_service_bcd_service_unpush_args_finalize (GObject *object)
{
  edu_rice_bold_serviceBcdServiceUnpushArgs *tobject = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
edu_rice_bold_service_bcd_service_unpush_args_class_init (edu_rice_bold_serviceBcdServiceUnpushArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = edu_rice_bold_service_bcd_service_unpush_args_read;
  struct_class->write = edu_rice_bold_service_bcd_service_unpush_args_write;

  gobject_class->finalize = edu_rice_bold_service_bcd_service_unpush_args_finalize;
  gobject_class->get_property = edu_rice_bold_service_bcd_service_unpush_args_get_property;
  gobject_class->set_property = edu_rice_bold_service_bcd_service_unpush_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_UNPUSH_ARGS_XID,
     g_param_spec_int ("xid",
                       NULL,
                       NULL,
                       G_MININT32,
                       G_MAXINT32,
                       0,
                       G_PARAM_READWRITE));
}

GType
edu_rice_bold_service_bcd_service_unpush_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (edu_rice_bold_serviceBcdServiceUnpushArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) edu_rice_bold_service_bcd_service_unpush_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (edu_rice_bold_serviceBcdServiceUnpushArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) edu_rice_bold_service_bcd_service_unpush_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "edu_rice_bold_serviceBcdServiceUnpushArgsType",
                                   &type_info, 0);
  }

  return type;
}

