/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "edu_rice_bold_service_bcd_service.h"

gboolean
edu_rice_bold_service_bcd_service_if_push (edu_rice_bold_serviceBcdServiceIf *iface, edu_rice_bold_servicePushReply ** _return, const edu_rice_bold_serviceServerID master, const GHashTable * slaves, const edu_rice_bold_serviceBcdInfo * data, GError **error)
{
  return EDU_RICE_BOLD_SERVICE_BCD_SERVICE_IF_GET_INTERFACE (iface)->push (iface, _return, master, slaves, data, error);
}

gboolean
edu_rice_bold_service_bcd_service_if_unpush (edu_rice_bold_serviceBcdServiceIf *iface, const gint32 xid, GError **error)
{
  return EDU_RICE_BOLD_SERVICE_BCD_SERVICE_IF_GET_INTERFACE (iface)->unpush (iface, xid, error);
}

GType
edu_rice_bold_service_bcd_service_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (edu_rice_bold_serviceBcdServiceIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "edu_rice_bold_serviceBcdServiceIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
edu_rice_bold_service_bcd_service_if_interface_init (edu_rice_bold_serviceBcdServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (edu_rice_bold_serviceBcdServiceClient, edu_rice_bold_service_bcd_service_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (EDU_RICE_BOLD_SERVICE_TYPE_BCD_SERVICE_IF,
                                                edu_rice_bold_service_bcd_service_if_interface_init))

enum _edu_rice_bold_serviceBcdServiceClientProperties
{
  PROP_0,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT_INPUT_PROTOCOL,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT_OUTPUT_PROTOCOL
};

void
edu_rice_bold_service_bcd_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServiceClient *client = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
edu_rice_bold_service_bcd_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServiceClient *client = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean edu_rice_bold_service_bcd_service_client_send_push (edu_rice_bold_serviceBcdServiceIf * iface, const edu_rice_bold_serviceServerID master, const GHashTable * slaves, const edu_rice_bold_serviceBcdInfo * data, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "push", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "push_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "master", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, master, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "slaves", T_SET, 2, error)) < 0)
      return 0;
    xfer += ret;
    {
      GList *key_list = NULL, *iter = NULL;
      edu_rice_bold_serviceServerID* keys;
      int i = 0, key_count;
      edu_rice_bold_serviceServerID elem;
      gpointer value;
      THRIFT_UNUSED_VAR (value);

      if ((ret = thrift_protocol_write_set_begin (protocol, T_STRING, (gint32) g_hash_table_size ((GHashTable *) slaves), error)) < 0)
        return 0;
      xfer += ret;
      g_hash_table_foreach ((GHashTable *) slaves, thrift_hash_table_get_keys, &key_list);
      key_count = g_list_length (key_list);
      keys = g_newa (edu_rice_bold_serviceServerID, key_count);
      for (iter = g_list_first (key_list); iter; iter = iter->next)
        keys[i++] = (edu_rice_bold_serviceServerID) iter->data;
      g_list_free (key_list);

      for (i = 0; i < key_count; ++i)
      {
        elem = keys[i];
        value = (gpointer) g_hash_table_lookup (((GHashTable *) slaves), (gpointer) elem);

        if ((ret = thrift_protocol_write_string (protocol, elem, error)) < 0)
          return 0;
      }
      if ((ret = thrift_protocol_write_set_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "data", T_STRUCT, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (data), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean edu_rice_bold_service_bcd_service_client_recv_push (edu_rice_bold_serviceBcdServiceIf * iface, edu_rice_bold_servicePushReply ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "push", 4) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected push", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean edu_rice_bold_service_bcd_service_client_push (edu_rice_bold_serviceBcdServiceIf * iface, edu_rice_bold_servicePushReply ** _return, const edu_rice_bold_serviceServerID master, const GHashTable * slaves, const edu_rice_bold_serviceBcdInfo * data, GError ** error)
{
  if (!edu_rice_bold_service_bcd_service_client_send_push (iface, master, slaves, data, error))
    return FALSE;
  if (!edu_rice_bold_service_bcd_service_client_recv_push (iface, _return, error))
    return FALSE;
  return TRUE;
}

gboolean edu_rice_bold_service_bcd_service_client_send_unpush (edu_rice_bold_serviceBcdServiceIf * iface, const gint32 xid, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "unpush", T_ONEWAY, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "unpush_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "xid", T_I32, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, xid, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean edu_rice_bold_service_bcd_service_client_unpush (edu_rice_bold_serviceBcdServiceIf * iface, const gint32 xid, GError ** error)
{
  if (!edu_rice_bold_service_bcd_service_client_send_unpush (iface, xid, error))
    return FALSE;
  return TRUE;
}

static void
edu_rice_bold_service_bcd_service_if_interface_init (edu_rice_bold_serviceBcdServiceIfInterface *iface)
{
  iface->push = edu_rice_bold_service_bcd_service_client_push;
  iface->unpush = edu_rice_bold_service_bcd_service_client_unpush;
}

static void
edu_rice_bold_service_bcd_service_client_init (edu_rice_bold_serviceBcdServiceClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
edu_rice_bold_service_bcd_service_client_class_init (edu_rice_bold_serviceBcdServiceClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = edu_rice_bold_service_bcd_service_client_set_property;
  gobject_class->get_property = edu_rice_bold_service_bcd_service_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
edu_rice_bold_service_bcd_service_handler_bcd_service_if_interface_init (edu_rice_bold_serviceBcdServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (edu_rice_bold_serviceBcdServiceHandler, 
                         edu_rice_bold_service_bcd_service_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (EDU_RICE_BOLD_SERVICE_TYPE_BCD_SERVICE_IF,
                                                edu_rice_bold_service_bcd_service_handler_bcd_service_if_interface_init))

gboolean edu_rice_bold_service_bcd_service_handler_push (edu_rice_bold_serviceBcdServiceIf * iface, edu_rice_bold_servicePushReply ** _return, const edu_rice_bold_serviceServerID master, const GHashTable * slaves, const edu_rice_bold_serviceBcdInfo * data, GError ** error)
{
  g_return_val_if_fail (EDU_RICE_BOLD_SERVICE_IS_BCD_SERVICE_HANDLER (iface), FALSE);

  return EDU_RICE_BOLD_SERVICE_BCD_SERVICE_HANDLER_GET_CLASS (iface)->push (iface, _return, master, slaves, data, error);
}

gboolean edu_rice_bold_service_bcd_service_handler_unpush (edu_rice_bold_serviceBcdServiceIf * iface, const gint32 xid, GError ** error)
{
  g_return_val_if_fail (EDU_RICE_BOLD_SERVICE_IS_BCD_SERVICE_HANDLER (iface), FALSE);

  return EDU_RICE_BOLD_SERVICE_BCD_SERVICE_HANDLER_GET_CLASS (iface)->unpush (iface, xid, error);
}

static void
edu_rice_bold_service_bcd_service_handler_bcd_service_if_interface_init (edu_rice_bold_serviceBcdServiceIfInterface *iface)
{
  iface->push = edu_rice_bold_service_bcd_service_handler_push;
  iface->unpush = edu_rice_bold_service_bcd_service_handler_unpush;
}

static void
edu_rice_bold_service_bcd_service_handler_init (edu_rice_bold_serviceBcdServiceHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
edu_rice_bold_service_bcd_service_handler_class_init (edu_rice_bold_serviceBcdServiceHandlerClass *cls)
{
  cls->push = NULL;
  cls->unpush = NULL;
}

enum _edu_rice_bold_serviceBcdServiceProcessorProperties
{
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR_0,
  PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (edu_rice_bold_serviceBcdServiceProcessor,
               edu_rice_bold_service_bcd_service_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* edu_rice_bold_serviceBcdServiceProcessorProcessFunction) (edu_rice_bold_serviceBcdServiceProcessor *, 
                                                                              gint32,
                                                                              ThriftProtocol *,
                                                                              ThriftProtocol *,
                                                                              GError **);

typedef struct
{
  gchar *name;
  edu_rice_bold_serviceBcdServiceProcessorProcessFunction function;
} edu_rice_bold_service_bcd_service_processor_process_function_def;

static gboolean
edu_rice_bold_service_bcd_service_processor_process_push (edu_rice_bold_serviceBcdServiceProcessor *,
                                                          gint32,
                                                          ThriftProtocol *,
                                                          ThriftProtocol *,
                                                          GError **);
static gboolean
edu_rice_bold_service_bcd_service_processor_process_unpush (edu_rice_bold_serviceBcdServiceProcessor *,
                                                            gint32,
                                                            ThriftProtocol *,
                                                            ThriftProtocol *,
                                                            GError **);

static edu_rice_bold_service_bcd_service_processor_process_function_def
edu_rice_bold_service_bcd_service_processor_process_function_defs[2] = {
  {
    "push",
    edu_rice_bold_service_bcd_service_processor_process_push
  },
  {
    "unpush",
    edu_rice_bold_service_bcd_service_processor_process_unpush
  }
};

static gboolean
edu_rice_bold_service_bcd_service_processor_process_push (edu_rice_bold_serviceBcdServiceProcessor *self,
                                                          gint32 sequence_id,
                                                          ThriftProtocol *input_protocol,
                                                          ThriftProtocol *output_protocol,
                                                          GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  edu_rice_bold_serviceBcdServicePushArgs * args =
    g_object_new (EDU_RICE_BOLD_SERVICE_TYPE_BCD_SERVICE_PUSH_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    edu_rice_bold_serviceServerID master;
    GHashTable * slaves;
    edu_rice_bold_serviceBcdInfo * data;
    edu_rice_bold_servicePushReply * return_value;
    edu_rice_bold_serviceBcdServicePushResult * result_struct;

    g_object_get (args,
                  "master", &master,
                  "slaves", &slaves,
                  "data", &data,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (EDU_RICE_BOLD_SERVICE_TYPE_BCD_SERVICE_PUSH_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (edu_rice_bold_service_bcd_service_handler_push (EDU_RICE_BOLD_SERVICE_BCD_SERVICE_IF (self->handler),
                                                        &return_value,
                                                        master,
                                                        slaves,
                                                        data,
                                                        error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "push",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("BcdService.push implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "push",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (master != NULL)
      g_free (master);
    if (slaves != NULL)
      g_hash_table_unref (slaves);
    if (data != NULL)
      g_object_unref (data);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
edu_rice_bold_service_bcd_service_processor_process_unpush (edu_rice_bold_serviceBcdServiceProcessor *self,
                                                            gint32 sequence_id,
                                                            ThriftProtocol *input_protocol,
                                                            ThriftProtocol *output_protocol,
                                                            GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  edu_rice_bold_serviceBcdServiceUnpushArgs * args =
    g_object_new (EDU_RICE_BOLD_SERVICE_TYPE_BCD_SERVICE_UNPUSH_ARGS, NULL);

  THRIFT_UNUSED_VAR (sequence_id);
  THRIFT_UNUSED_VAR (output_protocol);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gint xid;

    g_object_get (args,
                  "xid", &xid,
                  NULL);

    if (edu_rice_bold_service_bcd_service_handler_unpush (EDU_RICE_BOLD_SERVICE_BCD_SERVICE_IF (self->handler),
                                                          xid,
                                                          error) == TRUE)
    {
    }
    else
    {
      if (*error == NULL)
        g_warning ("BcdService.unpush implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "unpush",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
edu_rice_bold_service_bcd_service_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                                           ThriftProtocol *input_protocol,
                                                           ThriftProtocol *output_protocol,
                                                           gchar *method_name,
                                                           gint32 sequence_id,
                                                           GError **error)
{
  edu_rice_bold_service_bcd_service_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  edu_rice_bold_serviceBcdServiceProcessor *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
edu_rice_bold_service_bcd_service_processor_set_property (GObject *object,
                                                          guint property_id,
                                                          const GValue *value,
                                                          GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServiceProcessor *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_bold_service_bcd_service_processor_get_property (GObject *object,
                                                          guint property_id,
                                                          GValue *value,
                                                          GParamSpec *pspec)
{
  edu_rice_bold_serviceBcdServiceProcessor *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
edu_rice_bold_service_bcd_service_processor_dispose (GObject *gobject)
{
  edu_rice_bold_serviceBcdServiceProcessor *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (edu_rice_bold_service_bcd_service_processor_parent_class)->dispose (gobject);
}

static void
edu_rice_bold_service_bcd_service_processor_finalize (GObject *gobject)
{
  edu_rice_bold_serviceBcdServiceProcessor *self = EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR (gobject);

  g_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (edu_rice_bold_service_bcd_service_processor_parent_class)->finalize (gobject);
}

static void
edu_rice_bold_service_bcd_service_processor_init (edu_rice_bold_serviceBcdServiceProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 2; index += 1)
    g_hash_table_insert (self->process_map,
                         edu_rice_bold_service_bcd_service_processor_process_function_defs[index].name,
                         &edu_rice_bold_service_bcd_service_processor_process_function_defs[index]);
}

static void
edu_rice_bold_service_bcd_service_processor_class_init (edu_rice_bold_serviceBcdServiceProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = edu_rice_bold_service_bcd_service_processor_dispose;
  gobject_class->finalize = edu_rice_bold_service_bcd_service_processor_finalize;
  gobject_class->set_property = edu_rice_bold_service_bcd_service_processor_set_property;
  gobject_class->get_property = edu_rice_bold_service_bcd_service_processor_get_property;

  dispatch_processor_class->dispatch_call = edu_rice_bold_service_bcd_service_processor_dispatch_call;
  cls->dispatch_call = edu_rice_bold_service_bcd_service_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    EDU_RICE_BOLD_SERVICE_TYPE_BCD_SERVICE_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EDU_RICE_BOLD_SERVICE_BCD_SERVICE_PROCESSOR_HANDLER,
                                   param_spec);
}
